log_paths:
  - /var/log/messages
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  sender: debashiskundu2026@gamil.com
  password: HelloGmail@2000
  receiver: debashis.kundu@capgemini.com
ollama:
  model: qwen2.5:3b
